---
- hosts: all
  gather_facts: True
  become: yes
  tasks:
  - name: Ensure all packages are up to date
    apt:
      update_cache: yes
      upgrade: 'yes'
    register: apt_result

#  - name: Check if reboot is needed
#    stat:
#      path: /var/run/reboot-required
#    register: reboot_required

#  - name: Notify Slack if a reboot is needed
#    slack:
#      token: 'your-slack-token'
#      msg: 'Reboot is needed on {{ ansible_hostname }}'
#      channel: '#your-channel'
#    when: reboot_required.stat.exists