---
- name: Copy SSH public key from GitHub to authorized_keys
  hosts: all
  become: yes

  vars:
    remote_user: ross
    github_user: rosslopez

  tasks:
    - name: Install zsh
      apt:
        name: zsh
        state: present

    - name: Install git
      apt:
        name: git
        state: present

    - name: Install Oh My Zsh for the user
      become_user: "{{ remote_user }}"
      shell: >
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        executable: /bin/bash
      environment:
        RUNZSH: 'no'
        CHSH: 'no'
      become: yes
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
    
    - name: Ensure the user account exists
      user:
        name: "{{ remote_user }}"
        state: present
        create_home: yes
        shell: /bin/zsh

    - name: Fetch SSH public key from GitHub
      uri:
        url: "https://github.com/{{ github_user }}.keys"
        return_content: yes
      register: github_key

    - name: Ensure .ssh directory exists for the user
      become_user: "{{ remote_user }}"
      file:
        path: "/home/{{ remote_user }}/.ssh"
        state: directory
        mode: "0700"

    - name: Add GitHub SSH public key to authorized_keys
      become_user: "{{ remote_user }}"
      lineinfile:
        path: "/home/{{ remote_user }}/.ssh/authorized_keys"
        line: "{{ github_key.content }}"
        create: yes
        state: present
        mode: "0600"

    - name: Ensure 'ross' has sudo privileges
      lineinfile:
        path: "/etc/sudoers.d/90-ross"
        line: "ross ALL=(ALL) NOPASSWD:ALL"
        state: present
        create: yes
        validate: 'visudo -cf %s'
